name: carshop
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  intl: ^0.15.7
  datetime_picker_formfield: ^1.0.0
  shared_preferences: ^0.5.3+4
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_slider: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
   - assets/appimages/bg.jpeg

   - assets/login/bg_login.jpg
   - assets/login/login.png

   - assets/slider/

   - assets/logo/Audi.png
   - assets/logo/BMW.jpg
   - assets/logo/Ford.png
   - assets/logo/Honda.jpg
   - assets/logo/Mazda.jpg
   - assets/logo/Mercedes-Benz.png
   - assets/logo/Mitsubishi.png
   - assets/logo/Nissan.jpg
   - assets/logo/Suzuki.png
   - assets/logo/Toyota.jpg
   - assets/logo/Wuling.png

   - assets/Cars/MERCEDES BENZ/Mercedes Benz A-Class.jpg
   - assets/Cars/MERCEDES BENZ/Mercedes Benz CLS-Class.jpg

   - assets/Cars/BMW/BMW 7 Series Sedan.jpg
   - assets/Cars/BMW/BMW M5.jpg

   - assets/Cars/AUDI/Audi A7.jpg
   - assets/Cars/AUDI/Audi R8.jpg

   - assets/Cars/HONDA/Honda Civic Type R.jpg
   - assets/Cars/HONDA/Honda Accord.jpg

   - assets/Cars/MAZDA/Mazda 6.jpg
   - assets/Cars/MAZDA/Mazda MX 5 RF.jpg

   - assets/Cars/MITSUBISHI/Mitsubishi Xpander Cross.jpg
   - assets/Cars/MITSUBISHI/Mitsubishi Pajero Sport.jpg

   - assets/Cars/NISSAN/Nissan Juke.jpg
   - assets/Cars/NISSAN/Nissan Terra.jpg

   - assets/Cars/SUZUKI/Suzuki Baleno.jpg
   - assets/Cars/SUZUKI/Suzuki SX4 S Cross.jpg

   - assets/Cars/TOYOTA/Toyota 86.jpg
   - assets/Cars/TOYOTA/Toyota GR Supra.jpg

   - assets/Cars/WULING/Wuling Almaz.jpg
   - assets/Cars/WULING/Wuling Cortez.jpg

   - assets/Cars/FORD/Ford All New Focus.jpeg
   - assets/Cars/FORD/Ford New Fiesta.jpg

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
